lanuage: php

php:
 - '7.1'

before_script:
  - cp .env.travis .env
  - composer self-update
  - composer install --prefer-source --no-interaction
  - php artisan key:generate
  - php artisan jwt:generate
  - php artisan migrate
  - pear install pear/PHP_CodeSniffer
  - npm install npm@latest -g
  - npm install -g jshint
  - npm install

script:
 - vendor/bin/phpunit --coverage-text
 - phpcs --ignore=app/Http/Controllers/Auth,app/Http/Controllers/Controller.php app/Http/Controllers
 - npm run production
 - jshint resources/assets/js/modules/*

matrix:
 - php: 7.1
   env: ZEND_BACKEND="--backend=ZendEngine3"
   install: sudo apt-get install php7.0-phalcon

notifications:
  email: false