os:
 - linux

lanuage:
 - php

php:
 - '7.1.3'

before_script:
 - composer self-update
 - composer install --no-interaction
 - cp .env.travis .env
 - phpenv rehash
 - npm install npm@latest -g
 - npm install -g jshint
 - npm install

script:
 - vendor/bin/phpunit --coverage-text
 - phpcs --ignore=app/Http/Controllers/Auth,app/Http/Controllers/Controller.php app/Http/Controllers
 - npm run production
 - jshint resources/assets/js/modules/*